---
# Playbook for webservers

- name: Install packages
  sudo: yes
  action: apt pkg={{item}} state=latest update_cache=yes
  with_items:
    - nginx
    - php5-fpm
    - php5-mcrypt
    - php5-pgsql

- name: ensure php5-fpm is running
  service: name=php5-fpm state=started
  sudo: yes

- name: ensure nginx is running
  service: name=nginx state=started
  sudo: yes

- name: remove default site
  sudo: yes
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

- name: remove default index.html
  sudo: yes
  action: file path=/etc/nginx/sites-enabled/index.html state=absent
  notify:
    - reload nginx

- name: add php.ini
  action: template src=php.ini dest=/etc/php5/fpm/php.ini
  sudo: yes
  notify:
    - restart fpm
    - restart nginx

- name: add www.conf
  action: template src=www.conf dest=/etc/php5/fpm/pool.d/www.conf
  sudo: yes
  notify:
    - restart fpm
    - restart nginx
