---
# The main playbook to deploy the cluster

#init our machines
- hosts: targets
  remote_user: vagrant
  tags:
    - init
  roles:
    - common

#setup our databases
- hosts: databases
  remote_user: vagrant
  tags:
    - setup_db
  roles:
    - postgresql

#setup cluster master
- hosts: databases_master
  remote_user: vagrant
  vars:
    db_name: cluster
    db_user: foobar
    db_pass: foobar
  tags:
    - setup_db_cluster
  roles:
    - pg_master

#setup cluster hot standby
- hosts: databases_slave
  remote_user: vagrant
  vars:
    db_name: cluster
    db_master: 192.168.22.12
  tags:
    - setup_db_cluster
  roles:
    - pg_slave

#setup our web servers
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    webroot: /var/www/cluster.dev/public
    servername: cluster.dev
  remote_user: vagrant
  tags:
    - setup_web
  roles:
    - nginx
    - app_web

#setup our load balancers
- hosts: load_balancers
  remote_user: vagrant
  tags:
    - setup_load_balancer
  roles:
    - varnish
