---
# The main playbook to deploy the cluster

#init our machines
- hosts: targets
  tags:
    - init
  roles:
    - common

#setup our databases
- hosts: databases
  tags:
    - setup_db
  roles:
    - postgresql

#setup cluster master
- hosts: databases_master
  tags:
    - setup_db_cluster
  roles:
    - pg_master

#setup cluster hot standby
- hosts: databases_slave
  tags:
    - setup_db_cluster
  roles:
    - pg_slave

#setup our web servers
- hosts: webservers
  tags:
    - setup_web
  roles:
    - nginx
    - app_web

#setup our load balancers
- hosts: load_balancers
  tags:
    - setup_load_balancer
  roles:
    - varnish
