---
# Playbook for app web servers

- name: create site configurations
  sudo: yes
  template: src=sites-available/{{ servername }}.j2 dest=/etc/nginx/sites-available/{{ servername }}

- name: enable site
  sudo: yes
  action: file state=link src=/etc/nginx/sites-available/{{ servername }} path=/etc/nginx/sites-enabled/{{ servername }}

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && sudo /bin/mv -f composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: set perms of /var/www
  sudo: yes
  file:
    path: /var/www
    owner: vagrant
    group: www-data
    mode: 0774
    state: directory

- name: get repo
  tags: [install_app, update_app]
  git: repo={{ repo }} accept_hostkey=true
       dest=/var/www/{{ servername }}

- name: composer update
  tags: [install_app, update_app]
  composer: prefer_dist=true working_dir=/var/www/{{ servername }}

- name: artisan migrate install
  tags: [install_app]
  shell: chdir=/var/www/{{ servername }} /usr/bin/php artisan migrate:install
  ignore_errors: yes

- name: artisan migrate
  tags: [install_app, update_app]
  shell: chdir=/var/www/{{ servername }} /usr/bin/php artisan migrate

- name: set permissions for web root
  tags: [install_app, update_app]
  sudo: yes
  file:
    path: /var/www/{{ servername }}
    owner: vagrant
    group: www-data
    mode: 0774
    recurse: true
    state: directory

- name: restart nginx
  service: name=nginx state=restarted
  sudo: yes
