---
# Tasks for common servers

- name: add id_rsa
  copy: content={{ private_key_vagrant }} dest=/home/vagrant/.ssh/id_rsa

- name: add id_rsa.pub
  copy: content={{ public_key_vagrant }} dest=/home/vagrant/.ssh/id_rsa.pub

- name: add host public key to authorized_keys
  authorized_key: user=vagrant state=present key="{{ host_public_key }}"

- name: set perms of .ssh
  sudo: yes
  file:
    path: /home/vagrant/.ssh
    owner: vagrant
    group: vagrant
    mode: 0700
    recurse: true

- name: update sources.list
  sudo: yes
  template: src=sources.list.j2 dest=/etc/apt/sources.list
