---
# Tasks for app database servers
- name: init db
  sudo_user: postgres
  sudo: yes
  postgresql_user: name={{ db_user }} password={{ db_pass }} role_attr_flags=CREATEDB

- name: setup db
  postgresql_db:
    name={{ db_name }}
    login_host=127.0.0.1
    login_password={{ db_pass }}
    login_user={{ db_user }}
    owner={{ db_user }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    state=present
